play_with_django/blog/urls.py
from django.conf.urls import url

from . import views
from . import views_cbv

urlpatterns = [
    url(r'^$', views_cbv.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^comments/$', views.comment_list, name='comment_list'),

    url(r'^cbv/new/$', views_cbv.post_new),
    url(r'^cbv/list/$', views_cbv.post_list),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),
]

play_with_django/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
# from django.views.generic import RedirectView

from config import settings

# def root(request):
#     return redirect('blog:post_list')


urlpatterns = [
    # url(r'^$', root, name='root'),
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    # url(r'^$', RedirectView.as_view(pattern_name='blog:post_list')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

play_with_django/blog/models.py
import re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.forms import ValidationError
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')


class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, help_text='please enter the post title. max length : 100 characters.')
    content = models.TextField()

    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
                                processors=[Thumbnail(300, 300)],
                                format='JPEG',
                                options={'quality': 60})

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, blank=True,
                              validators=[lnglat_validator],
                              help_text='longitude/latitude format insert')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

play_with_django/blog/forms.py
from django import forms

from config.widgets.naver_map_point_widget import NaverMapPointWidget
from .models import Post


class PostForm(forms.ModelForm):
    # dummy = forms.CharField(widget=NaverMapPointWidget(attrs={'width': "100%", 'height': 200}))

    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'lnglat': NaverMapPointWidget(attrs={'width': 600, 'height': 300}),
        }

play_with_django/blog/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post, Comment


def post_list(request):
    qs = Post.objects.all().prefetch_related('tag_set', 'comment_set')

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__icontains=q)

    # messages.error(request, 'error message test')

    return render(request, 'blog/post_list.html', {
        'post_list': qs, 'q': q,
    })


def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(Post, id=id)
    return render(request, 'blog/post_detail.html', {'post': post, })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post)  # post.get_absolute_url() -> post_detail
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form, })


def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅이 수정되었습니다.')
            return redirect(post)  # post.get_absolute_url() -> post_detail
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {'form': form, })


def comment_list(request):
    comment_list = Comment.objects.all().select_related('post')
    return render(request, 'blog/comment_list.html', {'comment_list': comment_list})

play_with_django/blog/templates/blog/comment_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <!-- blog/templates/blog/comment_list.html -->
    <ul>
    {% for comment in comment_list %}
    <li>
        {{ comment }}
        {{ comment.post }}
    </li>
    {% endfor %}
    </ul>
{% endblock %}

play_with_django/blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}Blog{% endblock %}

play_with_django/blog/templates/blog/post_confirm_delete.html
<h1>{{ post }} 삭제 확인</h1>

정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}">아니요. 취소!</a>
    <input type="submit" value="예. 삭제하겠습니다." />
</form>

play_with_django/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>

                <!--{# <img src="/media/{{ post.photo }}" alt="" style="max-width: 100%;"> #} 참고-->
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="" style="max-width: 100%;">

                    {% thumbnail "100x100" post.photo %}

                    {% thumbnail "100x100" post.photo as thumb %}
                    <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />

                    {% thumbnail "100x100" post.photo -- style="" onclick="" class="" %}
                {% endif %}

                {{ post.content|linebreaks }}

                <hr/>

                <h3>Comments</h3>

                <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.updated_at }}</small>kk
                    </li>
                {% endfor %}
                </ul>

                <hr/>
                <a href='{% url "blog:post_list" %}' class="btn btn-primary">List</a>
                <a href='{% url "blog:post_edit" post.id %}' class="btn btn-default">Edit</a>
            </div>
        </div>
    </div>
{% endblock %}

play_with_django/blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

play_with_django/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>My Blog <sup>by me</sup></h1>
        <p>Hello. This is My Blog.</p>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-info">
                <ul>
                    <li>
                        One
                    </li>
                    <li>
                        Two
                    </li>
                </ul>
            </div>

            <a href="{% url 'blog:post_new' %}" class="btn btn-primary pull-right">New Post</a>

            <p>
            <form action="" method="get">
                <input type="text" name="q" value="{{ q }}"/>
                <input type="submit" value="검색" class="btn btn-primary"/>
            </form>
            </p>
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th>id</th>
                    <th>title</th>
                    <th>author</th>
                    <th>updated_at</th>
                </tr>
                </thead>
                <tbody>
                {% for post in post_list %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td>
                        <a href='{% url "blog:post_detail" post.id %}'>{{ post.title }}</a>
                        {% for tag in post.tag_set.all %}
                            <span class="label label-info">{{ tag.name }}</span>
                        {% endfor %}
                    </td>
                    <td>
                        <small>by {{ post.author }}</small>
                    </td>
                    <td>
                        <small>at {{ post.updated_at }}</small>
                    </td>
                    <!--<td>-->
                        <!--{{ post.comment_set.all }}-->
                    <!--</td>-->
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}